server.port = 8081
spring.application.name=tiendita

#Conexión a la base de datos (usa variables de entorno)
spring.datasource.url = ${DB_URL:jdbc:mysql://localhost:3307/tiendita_db?useSSL=false&serverTimezone=UTC}
spring.datasource.username = ${DB_USER:root}
spring.datasource.password = ${DB_PASS:}
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

#Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true

#Configuración global de CORS para React
spring.mvc.cors.allowed-origins=${CORS_ORIGINS:http://localhost:5173}
spring.mvc.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=3600000

#API key de Stripe
stripe.apikey.secret=${STRIPE_SECRET_KEY}
